# baseURL: https://adibpr.github.io/
relativeURLS: true
canonifyurls: true
theme: mine
title: Adib.notes
languageCode: en-us
markup:
  highlight:
      style: monokai
ignoreFiles:
    - "notebook/.*"
